spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
  datasource:
        name: test
        url: jdbc:mysql://172.16.2.56:3306/yatai
        username: yatai
        password: yataiapp
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
       
  #Jedis配置
  jedis:
    pool:
      host: 127.0.0.1
      port: 6379
      password: 
      timeout: 0
      config:
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis: 100000
        
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bjb.springboot.bootdemo.dao

# 打印sql  
logging:  
  level:   
    com.bjb.springboot.bootdemo.dao: DEBUG  

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql